version: '3.8'
services:
  user-service:
    image: user-service:0.0.1
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    networks:
      - local-network

networks:
  local-network:
    external: true
